import { LitElement, PropertyValues, TemplateResult } from 'lit';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/select/filled-select.js';
import '@material/web/select/select-option.js';
import '@material/web/button/outlined-button.js';
import '@material/web/button/filled-button.js';
import '@material/web/menu/menu.js';
import '@material/web/menu/menu-item.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/icon/icon.js';
import '@material/web/tabs/tabs.js';
import '@material/web/tabs/primary-tab.js';
import '@material/web/switch/switch.js';
import '@material/mwc-snackbar';
import type { TextField } from '@material/web/textfield/internal/text-field.js';
type SwitchLink = {
    sourceSwitch: string;
    sourcePort: string;
    targetSwitch: string;
    targetPort: string;
};
export default class NetworkConfig extends LitElement {
    /** The document being edited as provided to plugins by [[`OpenSCD`]]. */
    doc: XMLDocument;
    docName: string;
    docVersion: string;
    prpNetwork: 'A' | 'B';
    protectionSystem: '1' | '2';
    nativeVlan: string;
    inputCsvData: string;
    substation: string;
    portData: {
        switchName: string;
        portName: string;
        iedName: string;
        receivingPortName: string;
    }[] | null;
    switchNames: string[];
    iedNames: string[];
    switchLinks: SwitchLink[];
    switchLinksInput: string;
    switchDiagramDot: string;
    showSwitchDiagram: boolean;
    includeIedInDiagram: boolean;
    diagramLayout: string;
    edgeRouting: string;
    diagramSpacing: string;
    vlanLabelFormat: 'dec' | 'hex';
    activeTabIndex: number;
    diagramZoom: number;
    diagramPanX: number;
    diagramPanY: number;
    isDiagramPanning: boolean;
    switchDiagramSvg: string;
    switchDiagramError: string;
    selectedPathStart: string;
    selectedPathEnd: string;
    highlightedEdgeKeys: string[];
    highlightedShortestEdgeKeys: string[];
    highlightedNodes: string[];
    pathTooltip: string;
    pathSelectionSummary: string;
    pathMetricsLabel: string;
    selectedLinkEdgeKey: string;
    selectedLinkSource: string;
    selectedLinkTarget: string;
    linkDetailsPinned: boolean;
    showGooseTraffic: boolean;
    showSvTraffic: boolean;
    iedDataError: string;
    switchLinksError: string;
    crossDatasetError: string;
    unusedIedCount: number;
    snackbarMessage: string;
    snackbarOpen: boolean;
    onlyConfigureIedPorts: boolean;
    configureSingleIedConnectivity: boolean;
    includePeerIedPortsForSingleIed: boolean;
    includeUnsubscribedMessages: boolean;
    selectedIedName: string;
    selectedSwitchScope: string;
    switchVendor: string;
    visualisationMenuOpen: boolean;
    downloadMenuOpen: boolean;
    usedControlBlocks: Map<Element, string[]> | null;
    private vizInstancePromise;
    private diagramRenderVersion;
    private diagramGraphEdges;
    private edgeLabelByKey;
    private _iedToSwitchCache;
    private _switchAdjacencyCache;
    private _switchPathCache;
    private _controlBlockAddressCache;
    private _linkTrafficCandidatesCache;
    private _connectedApAddressIndex;
    private _switchNameIndexCache;
    private diagramPanStartX;
    private diagramPanStartY;
    private diagramPanStartOffsetX;
    private diagramPanStartOffsetY;
    private diagramPanMoved;
    private suppressDiagramClick;
    private diagramActivePointerId;
    private colorSchemeMediaQuery;
    private readonly handleColorSchemeChange;
    private invalidateComputedCaches;
    private importType;
    inputUI: TextField;
    importCsvUI: HTMLInputElement;
    outputUI: TextField;
    ethernetSwitchUI: TextField;
    iedSelectUI: {
        value: string;
    };
    nativeVlanUI: TextField;
    visualisationMenuAnchorUI: HTMLElement;
    downloadMenuAnchorUI: HTMLElement;
    visualisationMenuUI: HTMLElement;
    downloadMenuUI: HTMLElement;
    connectedCallback(): void;
    disconnectedCallback(): void;
    refreshInputData(): void;
    updateSwitchNames(): void;
    updateIedNames(): void;
    private updateUnusedIedCount;
    private showSnackbar;
    private validateAcrossDatasets;
    refreshSwitchLinks(): void;
    private static resolveDiagramColor;
    private getDiagramThemeColors;
    buildSwitchDiagram(refreshLinks?: boolean, preserveSelection?: boolean): void;
    private rebuildDiagramForVlanLabelSizeChange;
    renderSwitchDiagramSvg(): Promise<void>;
    protected updated(changed: PropertyValues<this>): void;
    static getEdgeKey(source: string, target: string): string;
    static parseEdgeTitle(title: string): {
        source: string;
        target: string;
    } | null;
    decorateRenderedDiagram(): void;
    clearPathSelection(): void;
    private zoomDiagram;
    private resetDiagramView;
    private zoomToFit;
    private onDiagramWheel;
    private onDiagramPointerDown;
    private onDiagramPointerMove;
    private onDiagramPointerUp;
    private getNearestDiagramNodeName;
    private completePathSelection;
    onDiagramClick(event: Event): void;
    private applyPathHighlights;
    formatDirectedPath(pathNodes: string[]): string;
    applyPathHighlightingToDiagram(): void;
    downloadSwitchDiagramSvg(): void;
    downloadSwitchDiagramDot(): void;
    buildOutputConfiguration(): void;
    private refreshUsedControlBlocks;
    buildRuggedcomConfiguration(): void;
    buildCiscoConfiguration(): void;
    protected firstUpdated(): void;
    importData(): void;
    private static readonly PRIVATE_NS;
    private static readonly PRIVATE_NS_PREFIX;
    private static readonly PRIVATE_TYPE_IED;
    private static readonly PRIVATE_TYPE_SWITCH;
    /** Load IED and switch-link data saved as Private elements in the SCL doc. */
    private loadFromScl;
    /** Save IED and switch-link CSV data as Private elements in the SCL doc. */
    saveToScl(): void;
    private getAvailableSwitches;
    private getActiveScopeSummary;
    private static getServiceTypeForControlBlock;
    private getIedToSwitchIndex;
    private getSwitchAdjacency;
    private findSwitchPath;
    private buildConnectedApAddressIndex;
    private getControlBlockAddress;
    private getFlowEdgeKeys;
    private getSwitchNameIndex;
    private buildLinkTrafficCandidates;
    private buildSelectedLinkTrafficEntries;
    private isServiceTypeVisible;
    private filterEntriesBySelectedServices;
    private getSingleIedFocusHighlights;
    private getLinkSelectionIedHighlights;
    private getSingleIedFocusEdgeHighlights;
    private buildSingleIedSubscribedTrafficEntries;
    private static groupLinkTrafficEntries;
    private formatVlanForDisplay;
    private clearSelectedLink;
    private selectDiagramEdge;
    private renderSelectionChips;
    private renderLinkDetailsPane;
    private renderDiagramHostContent;
    private renderDiagramMetrics;
    private renderDiagramContent;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
export {};
